### ISSUE TITLE
FUSE Options?

### ISSUE THREAD

**Issue by sidanya** [darenliang/dsfs#1]
I can't find an option to add arguments to FUSE. For example allow_other, allow_root, nonempty and others. Is it possible and, if not, is it planned?

**Comment by darenliang** [comment]
It is possible to add arguments. I've originally forwarded the arguments to FUSE, but because the mountpoint, server ID and token need to be specified, I left it out. I would like to add this functionality in, because its very useful for Linux and macOS environments.

I have two ideas in mind:

- Create an "args" argument and pass the FUSE arguments as a string (I think this solution is gross)
- Extract the mountpoint, server ID and token, forward the rest over to FUSE

If you have any ideas how to pass in FUSE options, please let me know.

**Comment by darenliang** [comment]
~~Can you try this patch?~~

~~Replace line at https://github.com/darenliang/dsfs/blob/master/main.go#L69 with,~~
```go
host.Mount(mount, flag.Args())
```

**Comment by darenliang** [comment]
Now -o options should be forwarded to FUSE. Please let me know if it does not work.
